version: "3.8"

services:
  mongodb: 
    image: mongo
    container_name: mongodb
    restart: always
    tty: true
    stdin_open: true
    # volumes:
    #   - ./data:/var/lib/mysql
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb